[package]
name = "punk_config"
authors = ["Dhushanthan S", "Suganth R"]
version = "0.1.0"
repository = "https://github.com/dhushanthan-s/punk-terminal"
edition.workspace = true
rust-version.workspace = true

[dependencies]
lazy_static = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }

[dependencies.punk_terminal]
path = "../punk_terminal"
version = "*"
