[package]
name = "punk_terminal"
version = "0.1.0"

[dependencies]
lazy_static = "1.4"
k_board = { version = "1.2.4", features = ["ctrl_lower_letter", "ctrl_upper_letter", "lower_letter", "f", "numbers", "standar", "ctrl_standar", "alt_lower_letter", "alt_upper_letter", "lower_letter", "upper_letter", "alt_gr_lower_letter", "alt_gr_upper_letter", "ctrl_numbers", "alt_numbers", "alt_gr_numbers"] }