[package]
name = "punk_gui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
autobins = false

[[bin]]
name = "punk"
path = "src/main.rs"

[dependencies]
bytemuck = { workspace = true }
fontdue = { workspace = true }
pollster = { workspace = true }
punk_terminal = { path = "../punk_terminal" }
punk_utils = { path = "../punk_utils" }
vte = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
