[package]
name = "punk_terminal"
authors = ["Dhushanthan S", "Suganth R"]
version = "0.1.0"
repository = "https://github.com/dhushanthan-s/punk-terminal"
edition.workspace = true
rust-version.workspace = true

[dependencies]
lazy_static = { workspace = true }
vte = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
